apiVersion: v1
kind: BuildConfig
metadata:
  creationTimestamp: null
  labels:
    app: java-web-server
  name: java-web-server
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: java-web-server:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    git:
      uri: git@180.189.42.59:admin1/java-web-server.git
    type: Git
  strategy:
    dockerStrategy:
      from:
        kind: ImageStreamTag
        name: registry.access.redhat.com/redhat-openjdk-18/openjdk18-openshift
    type: Docker
  successfulBuildsHistoryLimit: 5
status:
  lastVersion: 0