---
## This playbook creates pvs based on folders already created on nfs share. templates/generic-nfs-pv has the nfs folder details.
- hosts: masters
  become: true
  tasks:
  - block:
      - name: Create a temporary directory for pv/pvc
        file:
          path: /var/tmp/ocp_pvs
          state: directory
      - name: template pvs
        template: 
           src: generic-nfs-pv.j2
           dest: /var/tmp/ocp_pvs/pv{{ item }}-5g.yml
        with_sequence: start=3 end=9 stride=1 
      - name: Create pvs
        command: /usr/bin/oc --config=/etc/origin/master/admin.kubeconfigcreate -f /var/tmp/ocp_pvs/pv{{ item }}-5g.yml
        with_sequence: start=3 end=9 stride=1 
      - name: Print pvs
        shell: /usr/bin/oc --config=/etc/origin/master/admin.kubeconfigget pv
    when: ( inventory_hostname == groups.masters[0] )


