---
- hosts: nodes
  become: yes
  environment:
    PATH: "{{ ansible_env.PATH }}:/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/root/bin"

  tasks:
    - name: Explicitly define block device to use for Docker storage
      template:
        src: templates/docker-storage-setup.j2
        dest: /etc/sysconfig/docker-storage-setup

    - name: Install docker
      yum:
        name: docker-1.13.1
        state: present

    - name: 
      shell: >
        docker-storage-setup
