#!/usr/bin/ansible-playbook
---
- hosts: nodes
  become: yes
  gather_facts: no
  tasks:
  - name: Pull down static pod images
    vars:
      images:
      - registry.access.redhat.com/rhel7/etcd:3.2.22
      - registry.access.redhat.com/openshift3/ose-node:v3.10
      - registry.access.redhat.com/openshift3/ose-node:v3.10.45
      - registry.access.redhat.com/openshift3/ose-control-plane:v3.10
      - registry.access.redhat.com/openshift3/ose-pod:v3.10.45
    command: "docker pull {{ item }}"
    with_items: images

    #  - name: Set HTTP_PROXY/HTTPS_PROXY in /etc/sysconfig/docker
    #blockinfile:
    #  block: |
    #    HTTPS_PROXY=example.com
    #    HTTP_PROXY=example.com 
    #    NO_PROXY=example.com,x.x.x.x
    #  dest: /etc/sysconfig/docker
    #  create: yes

  - name: Set net.ipv4.ip_foward kernel parameter
    lineinfile:
      path: /etc/sysctl.conf
      regexp: net.ipv4.ip_forward
      line: net.ipv4.ip_forward = 1

  - name: Ensure NTP is synced
    block:
    - name: Stop ntpd
      systemd:
        name: ntpd
        state: stopped
    
    - name: Force ntp sync
      command: ntpd -qg
    
    - name: Start/enable ntpd
      systemd:
        name: ntpd
        state: started
        enabled: true
