#!/usr/bin/ansible-playbook
---
# https://docs.openshift.com/container-platform/3.10/install_config/http_proxies.html#proxying-docker-pull
- hosts: nodes
  gather_facts: no
  become: yes
  tasks:
  - name: Set HTTP_PROXY/HTTPS_PROXY in /etc/sysconfig/docker
    blockinfile:
      block: |
        HTTPS_PROXY=https://180.211.186.6:8050
        HTTP_PROXY=http://180.211.186.6:8050
        NO_PROXY=.us.dev.corp,wt.produbanus.corp,.cluster.local,.svc,localhost,127.0.0.1,172.30.0.1,180.211.25.109,180.211.25.105,180.211.25.106,22.250.26.237,22.250.26.229,22.250.26.230
      dest: /etc/sysconfig/docker
      create: yes
